site_name: PropperBot
site_author: PopperDevs
site_url: https://github.com/PopperDevs/PopperBot
copyright: '© 2020 PopperDevs MIT'
nav:
  - Home: index.md
  - Commands: commands.md
  - Changelog: changelog.md
  - License: LICENSE.md
